// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahdDtJJ4Iem-1_-tsl2VpPqIn99j5gxc',
    appId: '1:894968399503:web:fd2de7be3fd31ae7b152fa',
    messagingSenderId: '894968399503',
    projectId: 'flutter-banking-app-f137d',
    authDomain: 'flutter-banking-app-f137d.firebaseapp.com',
    storageBucket: 'flutter-banking-app-f137d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbstL0t3UGgjoTiuWTzEb_O7U8w8-hTe0',
    appId: '1:894968399503:android:c8a461e3c1a92e21b152fa',
    messagingSenderId: '894968399503',
    projectId: 'flutter-banking-app-f137d',
    storageBucket: 'flutter-banking-app-f137d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs_UdTFKLA58mAxD9vC4AkRPRkzCoXHtc',
    appId: '1:894968399503:ios:ea6a47556f478936b152fa',
    messagingSenderId: '894968399503',
    projectId: 'flutter-banking-app-f137d',
    storageBucket: 'flutter-banking-app-f137d.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs_UdTFKLA58mAxD9vC4AkRPRkzCoXHtc',
    appId: '1:894968399503:ios:ea6a47556f478936b152fa',
    messagingSenderId: '894968399503',
    projectId: 'flutter-banking-app-f137d',
    storageBucket: 'flutter-banking-app-f137d.firebasestorage.app',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahdDtJJ4Iem-1_-tsl2VpPqIn99j5gxc',
    appId: '1:894968399503:web:95902b5f684fc814b152fa',
    messagingSenderId: '894968399503',
    projectId: 'flutter-banking-app-f137d',
    authDomain: 'flutter-banking-app-f137d.firebaseapp.com',
    storageBucket: 'flutter-banking-app-f137d.firebasestorage.app',
  );

}